export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
// Catgory actions list
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'; 
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS'; 

export const ADD_CATEGORY = 'ADD_CATEGORY'; 
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'; 

export const GET_CATEGORY_DETAILS = 'GET_CATEGORY_DETAILS'; 
export const GET_CATEGORY_DETAILS_SUCCESS = 'GET_CATEGORY_DETAILS_SUCCESS'; 

export const DELETE_CATEGORY = 'DELETE_CATEGORY'; 
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'; 

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';


// Customer actions list
export const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST'; 
export const GET_CUSTOMER_LIST_SUCCESS = 'GET_CUSTOMER_LIST_SUCCESS'; 

export const ADD_CUSTOMER = 'ADD_CUSTOMER'; 
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS'; 

export const GET_CUSTOMER_DETAILS = 'GET_CUSTOMER_DETAILS';
export const GET_CUSTOMER_DETAILS_SUCCESS = 'GET_CUSTOMER_DETAILS_SUCCESS'; 

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'; 
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS'; 

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'; 
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'; 


// Brands

export const GET_BRAND_LIST = `GET_BRAND_LIST`;
export const GET_BRAND_LIST_SUCCESS = 'GET_BRAND_LIST_SUCCESS';

export const ADD_BRAND =      `ADD_BRAND`;
export const ADD_BRAND_SUCCESS =   'ADD_BRAND_SUCCESS';

export const GET_BRAND_DETAILS = 'GET_BRAND_DETAILS';
export const GET_BRAND_DETAILS_SUCCESS = 'GET_BRAND_DETAILS_SUCCESS'; 

export const DELETE_BRAND = 'DELETE_BRAND'; 
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS'; 

export const UPDATE_BRAND = 'UPDATE_BRAND'; 
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS'; 


// Colors

export const GET_COLOR_LIST = `GET_COLOR_LIST`;
export const GET_COLOR_LIST_SUCCESS = 'GET_COLOR_LIST_SUCCESS';

export const ADD_COLOR =      `ADD_COLOR`;
export const ADD_COLOR_SUCCESS =   'ADD_COLOR_SUCCESS';

export const GET_COLOR_DETAILS = 'GET_COLOR_DETAILS';
export const GET_COLOR_DETAILS_SUCCESS = 'GET_COLOR_DETAILS_SUCCESS'; 

export const DELETE_COLOR = 'DELETE_COLOR'; 
export const DELETE_COLOR_SUCCESS = 'DELETE_COLOR_SUCCESS'; 

export const UPDATE_COLOR = 'UPDATE_COLOR'; 
export const UPDATE_COLOR_SUCCESS = 'UPDATE_COLOR_SUCCESS'; 


// TYPES

export const GET_TYPE_LIST = `GET_TYPE_LIST`;
export const GET_TYPE_LIST_SUCCESS = 'GET_TYPE_LIST_SUCCESS';

export const ADD_TYPE =      `ADD_TYPE`;
export const ADD_TYPE_SUCCESS =   'ADD_TYPE_SUCCESS';

export const GET_TYPE_DETAILS = 'GET_TYPE_DETAILS';
export const GET_TYPE_DETAILS_SUCCESS = 'GET_TYPE_DETAILS_SUCCESS'; 

export const DELETE_TYPE = 'DELETE_TYPE'; 
export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS'; 

export const UPDATE_TYPE = 'UPDATE_TYPE'; 
export const UPDATE_TYPE_SUCCESS = 'UPDATE_TYPE_SUCCESS'; 


// Size

export const GET_SIZE_LIST = `GET_SIZE_LIST`;
export const GET_SIZE_LIST_SUCCESS = 'GET_SIZE_LIST_SUCCESS';

export const ADD_SIZE =      `ADD_SIZE`;
export const ADD_SIZE_SUCCESS =   'ADD_SIZE_SUCCESS';

export const GET_SIZE_DETAILS = 'GET_SIZE_DETAILS';
export const GET_SIZE_DETAILS_SUCCESS = 'GET_SIZE_DETAILS_SUCCESS'; 

export const DELETE_SIZE = 'DELETE_SIZE'; 
export const DELETE_SIZE_SUCCESS = 'DELETE_SIZE_SUCCESS'; 

export const UPDATE_SIZE = 'UPDATE_SIZE'; 
export const UPDATE_SIZE_SUCCESS = 'UPDATE_SIZE_SUCCESS'; 



// SUPPLIER

export const GET_SUPPLIER_LIST = `GET_SUPPLIER_LIST`;
export const GET_SUPPLIER_LIST_SUCCESS = 'GET_SUPPLIER_LIST_SUCCESS';

export const ADD_SUPPLIER =      `ADD_SUPPLIER`;
export const ADD_SUPPLIER_SUCCESS =   'ADD_SUPPLIER_SUCCESS';

export const GET_SUPPLIER_DETAILS = 'GET_SUPPLIER_DETAILS';
export const GET_SUPPLIER_DETAILS_SUCCESS = 'GET_SUPPLIER_DETAILS_SUCCESS'; 

export const DELETE_SUPPLIER = 'DELETE_SUPPLIER'; 
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS'; 

export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER'; 
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS'; 


// PRODUCTS

export const GET_PRODUCT_LIST = `GET_PRODUCT_LIST`;
export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';

export const ADD_PRODUCT =      `ADD_PRODUCT`;
export const ADD_PRODUCT_SUCCESS =   'ADD_PRODUCT_SUCCESS';

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'; 

export const DELETE_PRODUCT = 'DELETE_PRODUCT'; 
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'; 

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'; 
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'; 

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'; 
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS'; 


// TRANSCATION

export const GET_TRANSCATION_LIST = `GET_TRANSCATION_LIST`;
export const GET_TRANSCATION_LIST_SUCCESS = 'GET_TRANSCATION_LIST_SUCCESS';

export const ADD_TRANSCATION =      `ADD_TRANSCATION`;
export const ADD_TRANSCATION_SUCCESS =   'ADD_TRANSCATION_SUCCESS';

export const GET_TRANSCATION_DETAILS = 'GET_TRANSCATION_DETAILS';
export const GET_TRANSCATION_DETAILS_SUCCESS = 'GET_TRANSCATION_DETAILS_SUCCESS'; 

export const DELETE_TRANSCATION = 'DELETE_TRANSCATION'; 
export const DELETE_TRANSCATION_SUCCESS = 'DELETE_TRANSCATION_SUCCESS'; 

export const UPDATE_TRANSCATION = 'UPDATE_TRANSCATION'; 
export const UPDATE_TRANSCATION_SUCCESS = 'UPDATE_TRANSCATION_SUCCESS';

export const UPDATE_TRANSCATION_STATUS = 'UPDATE_TRANSCATION_STATUS'; 
export const UPDATE_TRANSCATION_STATUS_SUCCESS = 'UPDATE_TRANSCATION_STATUS_SUCCESS';


export const GET_PRODUCT_AVAILIBLITY = 'GET_PRODUCT_AVAILIBLITY'; 
export const GET_PRODUCT_AVAILIBLITY_SUCCESS = 'GET_PRODUCT_AVAILIBLITY_SUCCESS';



// OTHER

export const GET_OTHER_LIST = `GET_OTHER_LIST`;
export const GET_OTHER_LIST_SUCCESS = 'GET_OTHER_LIST_SUCCESS';

export const ADD_OTHER =      `ADD_OTHER`;
export const ADD_OTHER_SUCCESS =   'ADD_OTHER_SUCCESS';

export const GET_OTHER_DETAILS = 'GET_OTHER_DETAILS';
export const GET_OTHER_DETAILS_SUCCESS = 'GET_OTHER_DETAILS_SUCCESS'; 

export const DELETE_OTHER = 'DELETE_OTHER'; 
export const DELETE_OTHER_SUCCESS = 'DELETE_OTHER_SUCCESS'; 

export const UPDATE_OTHER = 'UPDATE_OTHER'; 
export const UPDATE_OTHER_SUCCESS = 'UPDATE_OTHER_SUCCESS'; 
