export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
// Catgory actions list
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'; 
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS'; 

export const ADD_CATEGORY = 'ADD_CATEGORY'; 
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'; 

export const GET_CATEGORY_DETAILS = 'GET_CATEGORY_DETAILS'; 
export const GET_CATEGORY_DETAILS_SUCCESS = 'GET_CATEGORY_DETAILS_SUCCESS'; 

export const DELETE_CATEGORY = 'DELETE_CATEGORY'; 
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'; 

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';


// Customer actions list
export const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST'; 
export const GET_CUSTOMER_LIST_SUCCESS = 'GET_CUSTOMER_LIST_SUCCESS';


export const GET_CUSTOMER_STATS= 'GET_CUSTOMER_STATS'; 
export const GET_CUSTOMER_STATS_SUCCESS = 'GET_CUSTOMER_STATS_SUCCESS';

export const ADD_CUSTOMER = 'ADD_CUSTOMER'; 
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS'; 

export const GET_CUSTOMER_DETAILS = 'GET_CUSTOMER_DETAILS';
export const GET_CUSTOMER_DETAILS_SUCCESS = 'GET_CUSTOMER_DETAILS_SUCCESS'; 

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'; 
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS'; 

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'; 
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'; 


// Brands

export const GET_BRAND_LIST = `GET_BRAND_LIST`;
export const GET_BRAND_LIST_SUCCESS = 'GET_BRAND_LIST_SUCCESS';

export const ADD_BRAND =      `ADD_BRAND`;
export const ADD_BRAND_SUCCESS =   'ADD_BRAND_SUCCESS';

export const GET_BRAND_DETAILS = 'GET_BRAND_DETAILS';
export const GET_BRAND_DETAILS_SUCCESS = 'GET_BRAND_DETAILS_SUCCESS'; 

export const DELETE_BRAND = 'DELETE_BRAND'; 
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS'; 

export const UPDATE_BRAND = 'UPDATE_BRAND'; 
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS'; 


// Colors

export const GET_COLOR_LIST = `GET_COLOR_LIST`;
export const GET_COLOR_LIST_SUCCESS = 'GET_COLOR_LIST_SUCCESS';

export const ADD_COLOR =      `ADD_COLOR`;
export const ADD_COLOR_SUCCESS =   'ADD_COLOR_SUCCESS';

export const GET_COLOR_DETAILS = 'GET_COLOR_DETAILS';
export const GET_COLOR_DETAILS_SUCCESS = 'GET_COLOR_DETAILS_SUCCESS'; 

export const DELETE_COLOR = 'DELETE_COLOR'; 
export const DELETE_COLOR_SUCCESS = 'DELETE_COLOR_SUCCESS'; 

export const UPDATE_COLOR = 'UPDATE_COLOR'; 
export const UPDATE_COLOR_SUCCESS = 'UPDATE_COLOR_SUCCESS'; 


// TYPES

export const GET_TYPE_LIST = `GET_TYPE_LIST`;
export const GET_TYPE_LIST_SUCCESS = 'GET_TYPE_LIST_SUCCESS';

export const ADD_TYPE =      `ADD_TYPE`;
export const ADD_TYPE_SUCCESS =   'ADD_TYPE_SUCCESS';

export const GET_TYPE_DETAILS = 'GET_TYPE_DETAILS';
export const GET_TYPE_DETAILS_SUCCESS = 'GET_TYPE_DETAILS_SUCCESS'; 

export const DELETE_TYPE = 'DELETE_TYPE'; 
export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS'; 

export const UPDATE_TYPE = 'UPDATE_TYPE'; 
export const UPDATE_TYPE_SUCCESS = 'UPDATE_TYPE_SUCCESS'; 


// Size

export const GET_SIZE_LIST = `GET_SIZE_LIST`;
export const GET_SIZE_LIST_SUCCESS = 'GET_SIZE_LIST_SUCCESS';

export const ADD_SIZE =      `ADD_SIZE`;
export const ADD_SIZE_SUCCESS =   'ADD_SIZE_SUCCESS';

export const GET_SIZE_DETAILS = 'GET_SIZE_DETAILS';
export const GET_SIZE_DETAILS_SUCCESS = 'GET_SIZE_DETAILS_SUCCESS'; 

export const DELETE_SIZE = 'DELETE_SIZE'; 
export const DELETE_SIZE_SUCCESS = 'DELETE_SIZE_SUCCESS'; 

export const UPDATE_SIZE = 'UPDATE_SIZE'; 
export const UPDATE_SIZE_SUCCESS = 'UPDATE_SIZE_SUCCESS'; 

// Catgory actions list
export const GET_PATTERN_LIST = 'GET_PATTERN_LIST'; 
export const GET_PATTERN_LIST_SUCCESS = 'GET_PATTERN_LIST_SUCCESS'; 

export const ADD_PATTERN = 'ADD_PATTERN'; 
export const ADD_PATTERN_SUCCESS = 'ADD_PATTERN_SUCCESS'; 

export const GET_PATTERN_DETAILS = 'GET_PATTERN_DETAILS'; 
export const GET_PATTERN_DETAILS_SUCCESS = 'GET_PATTERN_DETAILS_SUCCESS'; 

export const DELETE_PATTERN = 'DELETE_PATTERN'; 
export const DELETE_PATTERN_SUCCESS = 'DELETE_PATTERN_SUCCESS'; 

export const UPDATE_PATTERN = 'UPDATE_PATTERN';
export const UPDATE_PATTERN_SUCCESS = 'UPDATE_PATTERN_SUCCESS';

// LENGTH

export const GET_LENGTH_LIST = `GET_LENGTH_LIST`;
export const GET_LENGTH_LIST_SUCCESS = 'GET_LENGTH_LIST_SUCCESS';

export const ADD_LENGTH =      `ADD_LENGTH`;
export const ADD_LENGTH_SUCCESS =   'ADD_LENGTH_SUCCESS';

export const GET_LENGTH_DETAILS = 'GET_LENGTH_DETAILS';
export const GET_LENGTH_DETAILS_SUCCESS = 'GET_LENGTH_DETAILS_SUCCESS'; 

export const DELETE_LENGTH = 'DELETE_LENGTH'; 
export const DELETE_LENGTH_SUCCESS = 'DELETE_LENGTH_SUCCESS'; 

export const UPDATE_LENGTH = 'UPDATE_LENGTH'; 
export const UPDATE_LENGTH_SUCCESS = 'UPDATE_LENGTH_SUCCESS'; 


// SUPPLIER

export const GET_SUPPLIER_LIST = `GET_SUPPLIER_LIST`;
export const GET_SUPPLIER_LIST_SUCCESS = 'GET_SUPPLIER_LIST_SUCCESS';

export const ADD_SUPPLIER =      `ADD_SUPPLIER`;
export const ADD_SUPPLIER_SUCCESS =   'ADD_SUPPLIER_SUCCESS';

export const GET_SUPPLIER_DETAILS = 'GET_SUPPLIER_DETAILS';
export const GET_SUPPLIER_DETAILS_SUCCESS = 'GET_SUPPLIER_DETAILS_SUCCESS'; 

export const DELETE_SUPPLIER = 'DELETE_SUPPLIER'; 
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS'; 

export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER'; 
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS'; 


// PRODUCTS

export const GET_PRODUCT_LIST = `GET_PRODUCT_LIST`;
export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS';

export const ADD_PRODUCT =      `ADD_PRODUCT`;
export const ADD_PRODUCT_SUCCESS =   'ADD_PRODUCT_SUCCESS';

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'; 

export const DELETE_PRODUCT = 'DELETE_PRODUCT'; 
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'; 

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'; 
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'; 

export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'; 
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS'; 


export const BARCODE_PRODUCT = 'BARCODE_PRODUCT'; 
export const BARCODE_PRODUCT_SUCCESS = 'BARCODE_PRODUCT_SUCCESS'; 


// VARIANTS
export const GET_VARIANT_LIST = `GET_VARIANT_LIST`;
export const GET_VARIANT_LIST_SUCCESS = 'GET_VARIANT_LIST_SUCCESS';

export const ADD_VARIANT =      `ADD_VARIANT`;
export const ADD_VARIANT_SUCCESS =   'ADD_VARIANT_SUCCESS';

export const GET_VARIANT_DETAILS = 'GET_VARIANT_DETAILS';
export const GET_VARIANT_DETAILS_SUCCESS = 'GET_VARIANT_DETAILS_SUCCESS'; 

export const DELETE_VARIANT = 'DELETE_VARIANT'; 
export const DELETE_VARIANT_SUCCESS = 'DELETE_VARIANT_SUCCESS'; 

export const UPDATE_VARIANT = 'UPDATE_VARIANT'; 
export const UPDATE_VARIANT_SUCCESS = 'UPDATE_VARIANT_SUCCESS'; 

export const SEARCH_VARIANT = 'SEARCH_VARIANT'; 
export const SEARCH_VARIANT_SUCCESS = 'SEARCH_VARIANT_SUCCESS'; 



// PURCHASE
export const GET_PURCHASE_LIST = `GET_PURCHASE_LIST`;
export const GET_PURCHASE_LIST_SUCCESS = 'GET_PURCHASE_LIST_SUCCESS';

export const ADD_PURCHASE =      `ADD_PURCHASE`;
export const ADD_PURCHASE_SUCCESS =   'ADD_PURCHASE_SUCCESS';

export const GET_PURCHASE_DETAILS = 'GET_PURCHASE_DETAILS';
export const GET_PURCHASE_DETAILS_SUCCESS = 'GET_PURCHASE_DETAILS_SUCCESS'; 

export const DELETE_PURCHASE = 'DELETE_PURCHASE'; 
export const DELETE_PURCHASE_SUCCESS = 'DELETE_PURCHASE_SUCCESS'; 

export const UPDATE_PURCHASE = 'UPDATE_PURCHASE'; 
export const UPDATE_PURCHASE_SUCCESS = 'UPDATE_PURCHASE_SUCCESS'; 

export const SEARCH_PURCHASE = 'SEARCH_PURCHASE'; 
export const SEARCH_PURCHASE_SUCCESS = 'SEARCH_PURCHASE_SUCCESS'; 



export const VARIANT_PURCHASE = 'VARIANT_PURCHASE'; 
export const VARIANT_PURCHASE_SUCCESS = 'VARIANT_PURCHASE_SUCCESS'; 

export const SUPPLIER_PURCHASE = 'SUPPLIER_PURCHASE'; 
export const SUPPLIER_PURCHASE_SUCCESS = 'SUPPLIER_PURCHASE_SUCCESS'; 

export const VARIANT_SELL = 'VARIANT_SELL'; 
export const VARIANT_SELL_SUCCESS = 'VARIANT_SELL_SUCCESS'; 

export const SUPPLIER_SELL = 'SUPPLIER_SELL'; 
export const SUPPLIER_SELL_SUCCESS = 'SUPPLIER_SELL_SUCCESS'; 



// TRANSCATION

export const GET_TRANSCATION_LIST = `GET_TRANSCATION_LIST`;
export const GET_TRANSCATION_LIST_SUCCESS = 'GET_TRANSCATION_LIST_SUCCESS';


export const GET_TRANSCATION_CUSTOMER_LIST = `GET_TRANSCATION_CUSTOMER_LIST`;
export const GET_TRANSCATION_CUSTOMER_LIST_SUCCESS = 'GET_TRANSCATION_CUSTOMER_LIST_SUCCESS';


export const ADD_TRANSCATION =      `ADD_TRANSCATION`;
export const ADD_TRANSCATION_SUCCESS =   'ADD_TRANSCATION_SUCCESS';

export const GET_TRANSCATION_DETAILS = 'GET_TRANSCATION_DETAILS';
export const GET_TRANSCATION_DETAILS_SUCCESS = 'GET_TRANSCATION_DETAILS_SUCCESS'; 

export const DELETE_TRANSCATION = 'DELETE_TRANSCATION'; 
export const DELETE_TRANSCATION_SUCCESS = 'DELETE_TRANSCATION_SUCCESS'; 

export const UPDATE_TRANSCATION = 'UPDATE_TRANSCATION'; 
export const UPDATE_TRANSCATION_SUCCESS = 'UPDATE_TRANSCATION_SUCCESS';

export const UPDATE_TRANSCATION_STATUS = 'UPDATE_TRANSCATION_STATUS'; 
export const UPDATE_TRANSCATION_STATUS_SUCCESS = 'UPDATE_TRANSCATION_STATUS_SUCCESS';


export const GET_PRODUCT_AVAILIBLITY = 'GET_PRODUCT_AVAILIBLITY'; 
export const GET_PRODUCT_AVAILIBLITY_SUCCESS = 'GET_PRODUCT_AVAILIBLITY_SUCCESS';



// OTHER

export const GET_OTHER_LIST = `GET_OTHER_LIST`;
export const GET_OTHER_LIST_SUCCESS = 'GET_OTHER_LIST_SUCCESS';

export const ADD_OTHER =      `ADD_OTHER`;
export const ADD_OTHER_SUCCESS =   'ADD_OTHER_SUCCESS';

export const GET_OTHER_DETAILS = 'GET_OTHER_DETAILS';
export const GET_OTHER_DETAILS_SUCCESS = 'GET_OTHER_DETAILS_SUCCESS'; 

export const DELETE_OTHER = 'DELETE_OTHER'; 
export const DELETE_OTHER_SUCCESS = 'DELETE_OTHER_SUCCESS'; 

export const UPDATE_OTHER = 'UPDATE_OTHER'; 
export const UPDATE_OTHER_SUCCESS = 'UPDATE_OTHER_SUCCESS'; 


//

// OTHER

export const GET_BARCODE_LIST = `GET_BARCODE_LIST`;
export const GET_BARCODE_LIST_SUCCESS = 'GET_BARCODE_LIST_SUCCESS';

export const ADD_BARCODE =      `ADD_BARCODE`;
export const ADD_BARCODE_SUCCESS =   'ADD_BARCODE_SUCCESS';

export const GET_BARCODE_DETAILS = 'GET_BARCODE_DETAILS';
export const GET_BARCODE_DETAILS_SUCCESS = 'GET_BARCODE_DETAILS_SUCCESS'; 

export const DELETE_BARCODE = 'DELETE_BARCODE'; 
export const DELETE_BARCODE_SUCCESS = 'DELETE_BARCODE_SUCCESS'; 

export const UPDATE_BARCODE = 'UPDATE_BARCODE'; 
export const UPDATE_BARCODE_SUCCESS = 'UPDATE_BARCODE_SUCCESS'; 


// Dashboard


export const GET_TOP_SELLING = 'GET_TOP_SELLING'; 
export const GET_TOP_SELLING_SUCCESS = 'GET_TOP_SELLING_SUCCESS';

export const GET_CATEGORY_PRODUCT_COUNT = 'GET_CATEGORY_PRODUCT_COUNT'; 
export const GET_CATEGORY_PRODUCT_COUNT_SUCCESS = 'GET_CATEGORY_PRODUCT_COUNT_SUCCESS';

export const GET_DAY_WISE_TRANSCATION = 'GET_DAY_WISE_TRANSCATION'; 
export const GET_DAY_WISE_TRANSCATION_SUCCESS = 'GET_DAY_WISE_TRANSCATION_SUCCESS';



export const GET_MONTH_WISE_TRANSCATION = 'GET_MONTH_WISE_TRANSCATION'; 
export const GET_MONTH_WISE_TRANSCATION_SUCCESS = 'GET_MONTH_WISE_TRANSCATION_SUCCESS';


export const GET_STATS_DASHBOARD = 'GET_STATS_DASHBOARD'; 
export const GET_STATS_DASHBOARD_SUCCESS = 'GET_STATS_DASHBOARD_SUCCESS';

export const ALERT_NOTIFY = 'ALERT_NOTIFY';
export const ALERT_NOTIFY_SUCCESS = 'ALERT_NOTIFY_SUCCESS';

